### ISSUE TITLE
AggregateException with jsonp request

### ISSUE THREAD

**Issue by cmjacques** [filipw/AspNetWebApi-OutputCache#6]
Hi,

Thanks for making your code available. I've successfully used it in a couple of WebAPI projects.

However, I've just tried making a jsonp request (via jQuery) to my rest endpoint and am getting the following error on line 97 - "Cannot access a closed Stream". Looks like it's from the ReadAsStringAsync() method.

I don't get any errors when making the request from Fiddler or my C# client, only when jsonp is involved.

For now I've had to disable outputcache for the controller action in question.

Thanks,
Chris

**Comment by Daxez** [comment]
Still an issue in 0.10.0

```
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at System.Net.Http.HttpContent.<>c__DisplayClass21_0.<LoadIntoBufferAsync>b__0(Task copyTask)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at WebApi.OutputCache.V2.CacheOutputAttribute.<OnActionExecutedAsync>d__42.MoveNext()
```
